### ISSUE TITLE
Look at concurrency issues with reloading and electron

### ISSUE THREAD

**Issue by erikyuzwa** [slashman/jsrl#13]
- There are still issues with concurrency for the npm run electron:* tasks
- Must be a better solution for handling the reload of any changed source files while running Electron

**Comment by slashman** [comment]
No luck with my research on this trying to chain the scripts so that webpack runs first, completes packing, then yields to electron but keeps watching.

**Comment by erikyuzwa** [comment]
Yeah - I haven't had much luck either. I started a new issue to look at Electron Forge which *might* help out here?

**Comment by erikyuzwa** [comment]
closing this down. Pretty much hit a dead end.
