### ISSUE TITLE
Investigate the use of Electron Forge

### ISSUE THREAD

**Issue by erikyuzwa** [slashman/jsrl#16]
- Electron Forge v6 is out, and has been advertised as a "batteries included" solution for Electron
- Is this a more reliable option for local dev and packaging / distribution?
- https://www.electronjs.org/blog/forge-v6-release

**Comment by slashman** [comment]
I see it explicitly has "handling build logic for webpack bundles before application packaging;" but not sure if we should switch just for that; honestly I mostly use live reload on the web version. 🤔

**Comment by erikyuzwa** [comment]
yeah -- I don't want to try and replace one "problem" only to create 3 more

**Comment by erikyuzwa** [comment]
I'm thinking this approach might make it easier - but also wondering about a slight directional change. I'll create a new issue to gauge the mood.
